# Generated by Django 3.2.3 on 2021-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caosnews', '0002_remove_colaborador_fotocolaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
